export const cardsMock = [
  {
    id: 1,
    name: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: true,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 2,
    name: 'name 2',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: true,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 3,
    title: 'name 3',
    price: 123.122,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 4,
    title: 'name 5',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 4,
    name: 'name 4',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Timisoara',
    urlImage: 'url',
    isFavorite: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 7,
    title: 'name 7',
    price: 123.127,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 8,
    title: 'name 81',
    price: 123.182,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Constanta',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 9,
    title: 'name 19',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 10,
    title: 'name 01',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Constanta',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 11,
    title: 'name 11',
    price: 123.121,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 12,
    title: 'name2 1',
    price: 123.212,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 13,
    title: 'name3 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Bucuresti',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 14,
    title: 'name 41',
    price: 123.124,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 15,
    title: 'name 15',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Pitesti',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 16,
    title: 'name6 1',
    price: 123.612,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 17,
    title: 'name 17',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 18,
    title: 'name 18',
    price: 823.128,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Cluj',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 19,
    title: 'na9me 1',
    price: 923.192,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 20,
    title: 'nam0e 1',
    price: 223.122,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 21,
    title: 'name2 1',
    price: 212.123,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Satu Mare',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 22,
    title: 'name 22',
    price: 123.122,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 23,
    title: 'name 13',
    price: 323.122,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
  {
    id: 24,
    title: 'name 24',
    price: 423.123,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Iasi',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 25,
    title: 'name 55',
    price: 553.152,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: false,
  },
  {
    id: 26,
    title: 'nam6e 1',
    price: 663.126,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Bucuresti',
    urlImage: 'url',
    isFavorite: true,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: false,
    bigHouse: true,
  },
  {
    id: 27,
    title: 'name 177',
    price: 773.122,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
    smallHouse: true,
    bigHouse: false,
  },
];
