export const cardsMock = [
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Timisoara',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Constanta',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Constanta',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Bucuresti',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Pitesti',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Cluj',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Satu Mare',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Iasi',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Bucuresti',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
  {
    id: 1,
    title: 'name 1',
    price: 123.12,
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed voluptates ex facilis laboriosam. Architecto odio fugit corporis, commodi vero molestiae quos delectus reiciendis. Repellat nostrum laboriosam placeat error nobis aut.',
    location: 'Suceava',
    urlImage: 'url',
    isFavorite: false,
    displayWide: false,
    cretedBy: 'anndy',
    checked: false,
  },
];
